name: Microservices CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: iamsajo
  DOCKER_PASSWORD: Sajo@0000
  IMAGE_PREFIX: latest

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [fastapi-order, flask-payment, golang-main, golang-user, nodejs-product]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        echo "Docker Username: ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}"

      - name: Login to Docker Hub
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:latest ${{ matrix.service }}

      - name: Push Docker Image (Only on Merge)
        if: github.event_name == 'push'
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:latest
