name: Microservices CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_PREFIX: latest

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [fastapi-order, flask-payment, golang-main, golang-user, nodejs-product]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker with Secret
        run: |
          echo "${{ secrets.DOCKER_USERNAME }}" > ~/.docker/config.json

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.REGISTRY }}/workshop/${{ matrix.service }}:latest ${{ matrix.service }}

      - name: Push Docker Image
        run: |
          docker push ${{ env.REGISTRY }}/workshop/${{ matrix.service }}:latest
